### ISSUE TITLE
Improve logging so that deferral times are only shown if actually implemented

### ISSUE THREAD

**Issue by SecondSonConsulting** [SecondSonConsulting/Renew#13]
Currently deferral times are logged at the moment the script calculates them, which is confusing reading the logs because it will print a "deferUntil" date but that date may not actually get implemented.

Maybe only log these variables when the actual deferral function is called? This should quiet the logs quite a bit when deferrals are active or uptime is within threshold.

**Comment by BigMacAdmin** [comment]
logging greatly streamlined in v0.1.8
