### ISSUE TITLE
Additional Aggro/Normal Features

### ISSUE THREAD

**Issue by fogdogit-paul-s** [SecondSonConsulting/Renew#48]
Would be good to have the option to flag additional options for each notification window individually. 

For example, i would like to use the --blurscreen dialog flag **only** on the Aggro dialog!

Thanks and keep up the great work!

**Comment by BigMacAdmin** [comment]
`AdditionalAggressiveOptions` is already a feature (Just missing in the documentation),  but specific options for Normal mode is not. 

This is easy to implement in my next version, thank you.

**Comment by BigMacAdmin** [comment]
This was implemented with v.0.1.10
