### ISSUE TITLE
Allow us to hide the swiftdialog icon via the configuration profile

### ISSUE THREAD

**Issue by fogdogit-paul-s** [SecondSonConsulting/Renew#49]
Currently I seem to have to edit the actual script to hide the icon (I am using a banner instead of an icon).

changing line 234 to read `defaultDialogIcon="--icon none"`

Would be nice to be able to set this as a flag in the additional options!

**Comment by BigMacAdmin** [comment]
The ability to use `none` for the MessageIcon key in your configuration file is now documented here: https://github.com/SecondSonConsulting/Renew/wiki/OptionalArguments#messageicon
