### ISSUE TITLE
Typo in deadline documentation

### ISSUE THREAD

**Issue by fogdogit-paul-s** [SecondSonConsulting/Renew#62]
hey noticed a typo in the example here: https://github.com/SecondSonConsulting/Renew/wiki/Deployment-Strategies#deadline-mode

Currently says:

`<key>Deadline</key>
  <integer>30</key>`

Should say (I think!):

`<key>Deadline</key>
  <integer>30</integer>`

**Comment by BigMacAdmin** [comment]
Yes, thank you so much for pointing it out, appreciate all the feedback and input keep it up.
