### ISSUE TITLE
RequiredArguments:UptimeThreshold

### ISSUE THREAD

**Issue by ozzyvanbrunschot** [SecondSonConsulting/Renew#69]
Hi There,

Getting the error "RequiredArguments:UptimeThreshold"
Installed via Installomator, everything is in place (binary, log, LaunchAgent, Managed Pref)

Prefs via profile below

<img width="781" alt="Screenshot 2023-01-16 at 15 11 21" src="https://user-images.githubusercontent.com/49714558/212698429-b3d3f6cc-0a8a-4fc6-80c9-f24af22a1747.png">

Command and output

<img width="819" alt="Screenshot 2023-01-16 at 15 16 19" src="https://user-images.githubusercontent.com/49714558/212698902-a2d89198-2c00-4b62-bfdb-7950c8046c51.png">

Mon Jan 16 15:10:34 CET 2023: --dry-run used. Device will not restart during this run.
Mon Jan 16 15:10:34 CET 2023: ERROR: Required Argument missing: :RequiredArguments:UptimeThreshold
Mon Jan 16 15:15:05 CET 2023: ERROR: Required Argument missing: :RequiredArguments:UptimeThreshold

What I'm doing wrong here?
Thanks!

**Comment by BigMacAdmin** [comment]
It looks to me like you haven’t set the preference domain.

**Comment by ozzyvanbrunschot** [comment]
It's set, if it's the right one ;)

<img width="1241" alt="Screenshot 2023-01-16 at 17 42 15" src="https://user-images.githubusercontent.com/49714558/212728715-6cbb5f0d-27a5-429f-a8e1-e2e3c05f170a.png">

**Comment by BigMacAdmin** [comment]
Questions like this are more easily helped on Slack, if you can join there is a channel #renew. This is an issue with your profile, and not specifically with the project. 

If you could provide me the full output of these commands either here or as snippets in slack we can probably get it sorted:

`/bin/zsh -x /usr/local/Renew.sh —dry-run`

and 

`/usr/libexec/PlistBuddy -c “Print” “/Library/Managed Preferences/com.secondsonconsulting.renew.plist”`

**Comment by ozzyvanbrunschot** [comment]
Hi, Thanks!

I'm using your profile :)

Output:
/bin/zsh -x /usr/local/Renew.sh --dry-run
+/usr/local/Renew.sh:5> scriptVersion=1.0.1 
+/usr/local/Renew.sh:24> check_not_root
+check_not_root:4> [[+check_not_root:4> id -u
+check_not_root:4> [[ 503 = 0 ]]
+/usr/local/Renew.sh:30> currentUser=+/usr/local/Renew.sh:30> echo 'show State:/Users/ConsoleUser'
+/usr/local/Renew.sh:30> currentUser=+/usr/local/Renew.sh:30> scutil
+/usr/local/Renew.sh:30> currentUser=+/usr/local/Renew.sh:30> awk '/Name :/ { print $3 }'
+/usr/local/Renew.sh:30> currentUser=ovb 
+/usr/local/Renew.sh:33> userHomeFolder=+/usr/local/Renew.sh:33> dscl . -read /users/ovb NFSHomeDirectory
+/usr/local/Renew.sh:33> userHomeFolder=+/usr/local/Renew.sh:33> cut -d ' ' -f 2
+/usr/local/Renew.sh:33> userHomeFolder=/Users/ovb 
+/usr/local/Renew.sh:36> logDir='/Users/ovb/Library/Application Support/Renew' 
+/usr/local/Renew.sh:37> logFile='/Users/ovb/Library/Application Support/Renew/Renew.log' 
+/usr/local/Renew.sh:64> [ ! -d '/Users/ovb/Library/Application Support/Renew' ']'
+/usr/local/Renew.sh:69> touch '/Users/ovb/Library/Application Support/Renew/Renew.log'
+/usr/local/Renew.sh:72> logLength=+/usr/local/Renew.sh:72> wc -l
+/usr/local/Renew.sh:72> logLength=+/usr/local/Renew.sh:72> xargs
+/usr/local/Renew.sh:72> logLength=47 
+/usr/local/Renew.sh:73> [ 47 -ge 3000 ']'
+/usr/local/Renew.sh:81> renewConfig='/Library/Managed Preferences/com.secondsonconsulting.renew.plist' 
+/usr/local/Renew.sh:84> dialogPath=/usr/local/bin/dialog 
+/usr/local/Renew.sh:87> pBuddy=/usr/libexec/PlistBuddy 
+/usr/local/Renew.sh:90> userDeferralProfile=/Users/ovb/Library/Preferences/com.secondsonconsulting.renew.user.plist 
+/usr/local/Renew.sh:93> [ --dry-run '=' --version ']'
+/usr/local/Renew.sh:101> [ ! -f '/Library/Managed Preferences/com.secondsonconsulting.renew.plist' ']'
+/usr/local/Renew.sh:107> [ ! -e /usr/local/bin/dialog ']'
+/usr/local/Renew.sh:113> /usr/libexec/PlistBuddy -c 'Add :TestPerms integer 0' /Users/ovb/Library/Preferences/com.secondsonconsulting.renew.user.plist
+/usr/local/Renew.sh:114> /usr/libexec/PlistBuddy -c 'Delete :TestPerms' /Users/ovb/Library/Preferences/com.secondsonconsulting.renew.user.plist
+/usr/local/Renew.sh:188> [ --dry-run '=' --dry-run ']'
+/usr/local/Renew.sh:189> log_message '--dry-run used. Device will not restart during this run.'
+log_message:3> [ -e '/Users/ovb/Library/Application Support/Renew/Renew.log' ']'
+log_message:4> date
+log_message:4> /bin/echo 'Tue Jan 17 08:01:57 CET 2023: --dry-run used. Device will not restart during this run.'
+log_message:7> [ '' '=' 1 ']'
+/usr/local/Renew.sh:190> dryRun=1 
+/usr/local/Renew.sh:223> debug_message 'Validating user deferral profile plist'
+debug_message:3> [ 1 '=' 1 ']'
+debug_message:4> /bin/echo 'DEBUG: Validating user deferral profile plist'
DEBUG: Validating user deferral profile plist
+/usr/local/Renew.sh:224> /usr/libexec/PlistBuddy -c 'Print :CurrentDeferralCount' /Users/ovb/Library/Preferences/com.secondsonconsulting.renew.user.plist
+/usr/local/Renew.sh:225> /usr/libexec/PlistBuddy -c 'Print :NotificationCount' /Users/ovb/Library/Preferences/com.secondsonconsulting.renew.user.plist
+/usr/local/Renew.sh:226> /usr/libexec/PlistBuddy -c 'Print :ActiveDeferral' /Users/ovb/Library/Preferences/com.secondsonconsulting.renew.user.plist
+/usr/local/Renew.sh:228> [ '' '=' 1 ']'
+/usr/local/Renew.sh:232> debug_message 'User deferral profile plist validated successfully'
+debug_message:3> [ 1 '=' 1 ']'
+debug_message:4> /bin/echo 'DEBUG: User deferral profile plist validated successfully'
DEBUG: User deferral profile plist validated successfully
+/usr/local/Renew.sh:247> validate_required_argument :RequiredArguments:UptimeThreshold
+validate_required_argument:3> /usr/libexec/PlistBuddy -c 'Print :RequiredArguments:UptimeThreshold' '/Library/Managed Preferences/com.secondsonconsulting.renew.plist'
+validate_required_argument:5> log_message 'ERROR: Required Argument missing: :RequiredArguments:UptimeThreshold'
+log_message:3> [ -e '/Users/ovb/Library/Application Support/Renew/Renew.log' ']'
+log_message:4> date
+log_message:4> /bin/echo 'Tue Jan 17 08:01:57 CET 2023: ERROR: Required Argument missing: :RequiredArguments:UptimeThreshold'
+log_message:7> [ 1 '=' 1 ']'
+log_message:8> debug_message 'ERROR: Required Argument missing: :RequiredArguments:UptimeThreshold'
+debug_message:3> [ 1 '=' 1 ']'
+debug_message:4> /bin/echo 'DEBUG: ERROR: Required Argument missing: :RequiredArguments:UptimeThreshold'
DEBUG: ERROR: Required Argument missing: :RequiredArguments:UptimeThreshold
+validate_required_argument:5> exit 2

and

/usr/libexec/PlistBuddy -c "Print" "/Library/Managed Preferences/com.secondsonconsulting.renew.plist"
Dict {
    PayloadDisplayName = Renew Configuration
    PayloadScope = System
    PayloadType = Configuration
    PayloadContent = Array {
        Dict {
            PayloadIdentifier = com.secondsonconsulting.renew.5A990D16-50BF-4F03-91DD-CD435C86DF1E
            PayloadDisplayName = renew
            PayloadType = com.secondsonconsulting.renew
            PayloadVersion = 1
            RequiredArguments = Dict {
                DeferralDuration = 6
                MaximumDeferrals = 6
                UptimeThreshold = 4
                NotificationThreshold = 2
            }
            PayloadUUID = 5A990D16-50BF-4F03-91DD-CD435C86DF1E
        }
    }
    PayloadIdentifier = SecondSon.E37B3EC4-7BB2-4717-8627-02F002162FDB
    PayloadVersion = 1
    PayloadUUID = E37B3EC4-7BB2-4717-8627-02F002162FDB
}

Thanks

**Comment by BigMacAdmin** [comment]
There's something about the manner in which you're deploying your profile that's problematic. As a test, please install one of the test profiles locally on a device.

Renew supports the ProfilesManifests project for creating configurations, and there's a project which clones these to be Jamf json schema's. I'm not a jamf admin, and haven't tested, but I know a handful of jamf admins have this working successfully. Check here: https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/tree/main/manifests/ManagedPreferencesApplications

When properly deployed, the second command I provided you would return something like this:
```
/usr/libexec/PlistBuddy -c "Print" "/Library/Managed Preferences/com.secondsonconsulting.renew.plist"
Dict {
    RequiredArguments = Dict {
        DeferralDuration = 8
        MaximumDeferrals = -1
        UptimeThreshold = 14
        NotificationThreshold = -1
    }
    PayloadUUID = 5A990D16-50BF-4F03-91DD-CD435C86DF1E
}
```
