### ISSUE TITLE
Deadline argument

### ISSUE THREAD

**Issue by a-phe-lei-a** [SecondSonConsulting/Renew#70]
I may be wrong, but at no moment do I see the Deadline argument in the script. 

At what point do we retrieve the Deadline value from the configuration file?

**Comment by BigMacAdmin** [comment]
Assuming you're on a mac, you can use Command+F in any browser or text editor to search for a word within a file.

The word "Deadline" appears 9 times in the latest version of Renew.sh, perhaps you're looking at an old version from before this feature was added.

In any case, please open a new issue if you have a specific problem or question with this feature and provide details about your configuration, what you expect to be happening, and what is actually happening.

Providing output of this command can streamline diagnosing the issue: `/bin/zsh -x /usr/local/Renew.sh`

**Comment by a-phe-lei-a** [comment]
I'm sorry, the `git pull` had not retrieved the latest version and I had the script version Beta 0.1.8. Even a cmd-f search didn't find anything

**Comment by BigMacAdmin** [comment]
That explains it! Thanks for the follow up.
